language: php
php:
  - "hhvm"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - git clone --depth=50 --branch=master git://github.com/nsendetzky/arcavias-core.git ../arcavias-core
  - cd ../arcavias-core
  - mv ../ai-flow ext/
  - composer require "typo3/flow" "2.2.*"
  - composer install
script: "vendor/bin/phing -Ddir=ext/ai-flow testext && vendor/bin/phing -Ddir=ext/ai-flow checkext"
