sudo: false
language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4

env:
  - FLOW_VERSION=2.3.*
  - FLOW_VERSION=3.0.*
  - FLOW_VERSION=3.1.*

before_script:
  - git clone --depth=50 --branch=2016.10 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core
  - mv ../ai-flow ext/
  - travis_retry composer require "typo3/flow:${FLOW_VERSION}" "zendframework/zend-diactoros:~1.0"

script: "vendor/bin/phing -Ddir=ext/ai-flow coverageext checkext"

after_success:
  - php vendor/bin/coveralls -c ext/ai-flow/.coveralls.yml

matrix:
  fast_finish: true
  exclude:
    - php: 5.3
      env: "FLOW_VERSION=3.0.*"
    - php: 5.3
      env: "FLOW_VERSION=3.1.*"
    - php: 5.4
      env: "FLOW_VERSION=3.0.*"
    - php: 5.4
      env: "FLOW_VERSION=3.1.*"

