sudo: false
language: php

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - FLOW_VERSION=5.0.*
  - FLOW_VERSION=4.3.*

matrix:
  fast_finish: true

before_script:
  - git clone --depth=50 --branch=2019.04 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core
  - mv ../ai-flow ext/
  - travis_retry composer require "neos/flow:${FLOW_VERSION}" "zendframework/zend-diactoros:~1.0"

script: "vendor/bin/phing -Ddir=ext/ai-flow coverageext checkext"

after_success:
  - php vendor/bin/coveralls -c ext/ai-flow/.coveralls.yml

matrix:
  fast_finish: true
  exclude:
  - php: 7.0
    env: FLOW_VERSION=5.0.*
